"""Command-line interface.

volsurf analyze --ticker ^SPX --expiries 8 --out reports/SPX
volsurf demo --out reports/demo
volsurf validate --out docs/VALIDATION.md
volsurf price --spot 100 --strike 100 --maturity 1 --rate 0.05 --vol 0.2 --heston 0.04,2,0.04,0.5,-0.7
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

from .black_scholes import bsm_price
from .heston import HestonParams, heston_price_cos_spot, heston_price_integration
from .lattice import binomial_price
from .market_data import build_snapshot, fetch_yfinance_chain, synthetic_chain
from .monte_carlo import lsm_american_price, mc_european_gbm, mc_european_heston
from .pipeline import AnalysisConfig, run_analysis
from .report import write_report
from .validation import run_validation, to_markdown

DEMO_PARAMS = HestonParams(v0=0.028, kappa=2.5, theta=0.042, sigma=0.8, rho=-0.74)


def _config(args: argparse.Namespace) -> AnalysisConfig:
    return AnalysisConfig(
        calibration_method=args.calibration,
        run_hedging=not args.no_hedging,
        heston_hedge_paths=args.paths,
    )


def _finish(snapshot, args: argparse.Namespace) -> None:
    print(
        f"Snapshot: {snapshot.ticker} spot {snapshot.spot:,.2f}, {len(snapshot.expiries)} expiries, "
        f"{sum(len(e.quotes) for e in snapshot.expiries)} clean OTM quotes"
    )
    result = run_analysis(snapshot, _config(args))
    out = Path(args.out)
    path = write_report(result, out)
    result.calibration.residuals.to_csv(out / "heston_residuals.csv", index=False)
    snapshot.term_structure().to_csv(out / "term_structure.csv", index=False)
    if result.hedging_heston is not None:
        pd.concat([result.hedging_bs.summary(), result.hedging_heston.summary()]).to_csv(out / "hedging_summary.csv", index=False)
    print(f"Report: {path.resolve()}")


def cmd_analyze(args: argparse.Namespace) -> None:
    out = Path(args.out)
    if args.raw_csv:
        raw_path = Path(args.raw_csv)
        meta = json.loads(raw_path.with_suffix(".json").read_text(encoding="utf-8"))
        raw, spot, as_of = pd.read_csv(raw_path), float(meta["spot"]), datetime.fromisoformat(meta["as_of"])
        ticker = meta["ticker"]
        print(f"Replaying saved {ticker} chain from {raw_path} (captured {as_of:%Y-%m-%d %H:%M} UTC)")
    else:
        ticker = args.ticker
        print(f"Downloading {ticker} option chains ...")
        raw, spot, as_of = fetch_yfinance_chain(ticker, max_expiries=args.expiries)
        if args.save_raw:
            out.mkdir(parents=True, exist_ok=True)
            raw.to_csv(out / "raw_chain.csv", index=False)
            meta = {"ticker": ticker, "spot": spot, "as_of": as_of.isoformat()}
            (out / "raw_chain.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    snapshot = build_snapshot(raw, spot, as_of, ticker, "Yahoo Finance (delayed)")
    _finish(snapshot, args)


def cmd_demo(args: argparse.Namespace) -> None:
    print(f"Generating a synthetic option market from Heston {DEMO_PARAMS} ...")
    raw = synthetic_chain(DEMO_PARAMS, seed=args.seed)
    snapshot = build_snapshot(raw, 5000.0, datetime.now(timezone.utc), "SYNTHETIC", "synthetic Heston market with quote noise")
    _finish(snapshot, args)


def cmd_validate(args: argparse.Namespace) -> None:
    results = run_validation(fast=args.fast)
    table = to_markdown(results)
    print(table)
    if args.out:
        header = (
            "# Validation report\n\n"
            f"Generated by `volsurf validate` on {datetime.now(timezone.utc):%Y-%m-%d}. "
            "Every numerical engine is checked against a published reference value or an independent method.\n\n"
        )
        Path(args.out).write_text(header + table + "\n", encoding="utf-8")
    if not results["passed"].all():
        sys.exit(1)


def cmd_price(args: argparse.Namespace) -> None:
    s, k, t, r, q, v = args.spot, args.strike, args.maturity, args.rate, args.dividend, args.vol
    is_call = args.type == "call"
    rows = [
        ("Black-Scholes (analytic)", float(bsm_price(s, k, t, r, q, v, is_call)), None),
        ("Leisen-Reimer tree, 301 steps", binomial_price(s, k, t, r, q, v, is_call, steps=301), None),
        ("CRR tree, 2000 steps", binomial_price(s, k, t, r, q, v, is_call, steps=2000, method="crr"), None),
    ]
    mc = mc_european_gbm(s, k, t, r, q, v, is_call, 200_000, seed=1)
    rows.append(("Monte Carlo + control variate", mc.price, mc.std_error))
    rows.append(("American: Leisen-Reimer tree", binomial_price(s, k, t, r, q, v, is_call, american=True, steps=1001), None))
    lsm = lsm_american_price(s, k, t, r, q, v, is_call, 50, 100_000, seed=2)
    rows.append(("American: Longstaff-Schwartz", lsm.price, lsm.std_error))
    if args.heston:
        p = HestonParams.from_array([float(x) for x in args.heston.split(",")])
        forward = s * np.exp((r - q) * t)
        rows.append(("Heston: COS", float(heston_price_cos_spot(s, [k], t, r, q, p, is_call)[0]), None))
        rows.append(("Heston: Gil-Pelaez quadrature", heston_price_integration(forward, k, t, np.exp(-r * t), p, is_call), None))
        hmc = mc_european_heston(s, k, t, r, q, p, is_call, n_steps=100, n_paths=100_000, seed=3)
        rows.append(("Heston: QE Monte Carlo", hmc.price, hmc.std_error))
    width = max(len(name) for name, _, _ in rows)
    for name, price, se in rows:
        extra = f"  +- {se:.4f}" if se is not None else ""
        print(f"{name:<{width}}  {price:>12.6f}{extra}")


def cmd_greeks(args: argparse.Namespace) -> None:
    from .analytic import Carry, greeks

    carry = {
        "stock": Carry.stock(args.rate, args.dividend),
        "future": Carry.future(args.rate),
        "currency": Carry.currency(args.rate, args.dividend),
    }[args.underlying]
    g = greeks(args.spot, args.strike, args.maturity, carry.rate, carry.yield_, args.vol, args.type == "call")
    print(f"{carry.convention} {args.type}: S={args.spot} K={args.strike} T={args.maturity} r={carry.rate} q={carry.yield_}")
    for name, value in g.as_dict().items():
        print(f"  {name:<11} {float(value): .10f}")


def cmd_gallery(args: argparse.Namespace) -> None:
    from pathlib import Path

    from . import gallery

    written = gallery.build(args.out, only=args.only)
    Path("docs").mkdir(exist_ok=True)
    if args.only is None:
        Path("docs/GALLERY.md").write_text(gallery.markdown(), encoding="utf-8")
    print(f"{len(written)} charts written to {args.out}")


def cmd_chains(args: argparse.Namespace) -> None:
    from .market import chains

    if args.action == "fetch":
        for ticker in args.tickers:
            print(f"{ticker}: stored {chains.fetch(ticker)}")
        return
    stored = chains.snapshots()
    if not stored:
        print(f"no snapshots under {chains.data_root()}; run `volsurf chains fetch ^SPX`")
    for day, ticker in stored:
        chain = chains.load(ticker, day)
        expiries, quotes = len(chain.expiries()), len(chain.quotes)
        print(f"{day}  {ticker:<6} spot {chain.spot:>10,.2f}  {expiries:>3} expiries  {quotes:>6,} quotes")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="volsurf", description="Option pricing, volatility surfaces and Heston calibration.")
    sub = parser.add_subparsers(dest="command", required=True)

    def analysis_flags(p: argparse.ArgumentParser, default_out: str) -> None:
        p.add_argument("--out", default=default_out, help="output directory for report.html, figures and CSVs")
        p.add_argument("--calibration", choices=["multistart", "global"], default="multistart")
        p.add_argument("--paths", type=int, default=4000, help="Monte Carlo paths for the Heston hedging lab")
        p.add_argument("--no-hedging", action="store_true", help="skip the hedging simulation")

    analyze = sub.add_parser("analyze", help="full analysis of a live option chain from Yahoo Finance")
    analyze.add_argument("--ticker", default="^SPX")
    analyze.add_argument("--expiries", type=int, default=8)
    analyze.add_argument("--save-raw", action="store_true", help="also save the raw chain (CSV + JSON metadata) for replay")
    analyze.add_argument("--raw-csv", default=None, help="replay a chain saved with --save-raw instead of downloading")
    analysis_flags(analyze, "reports/live")
    analyze.set_defaults(func=cmd_analyze)

    demo = sub.add_parser("demo", help="offline analysis of a synthetic Heston market")
    demo.add_argument("--seed", type=int, default=7)
    analysis_flags(demo, "reports/demo")
    demo.set_defaults(func=cmd_demo)

    validate = sub.add_parser("validate", help="run the numerical validation suite")
    validate.add_argument("--out", default=None, help="write the results as Markdown")
    validate.add_argument("--fast", action="store_true")
    validate.set_defaults(func=cmd_validate)

    price = sub.add_parser("price", help="price one contract with every engine")
    price.add_argument("--spot", type=float, required=True)
    price.add_argument("--strike", type=float, required=True)
    price.add_argument("--maturity", type=float, required=True)
    price.add_argument("--rate", type=float, default=0.0)
    price.add_argument("--dividend", type=float, default=0.0)
    price.add_argument("--vol", type=float, required=True)
    price.add_argument("--type", choices=["call", "put"], default="call")
    price.add_argument("--heston", default=None, help="v0,kappa,theta,sigma,rho")
    price.set_defaults(func=cmd_price)

    greek = sub.add_parser("greeks", help="the price and seventeen Greeks of a European option")
    greek.add_argument("--spot", type=float, required=True)
    greek.add_argument("--strike", type=float, required=True)
    greek.add_argument("--maturity", type=float, required=True)
    greek.add_argument("--rate", type=float, default=0.0)
    greek.add_argument("--dividend", type=float, default=0.0, help="dividend yield, or the foreign rate for a currency")
    greek.add_argument("--vol", type=float, required=True)
    greek.add_argument("--type", choices=["call", "put"], default="call")
    greek.add_argument("--underlying", choices=["stock", "future", "currency"], default="stock")
    greek.set_defaults(func=cmd_greeks)

    charts = sub.add_parser("gallery", help="redraw the documentation's charts")
    charts.add_argument("--out", default="docs/images")
    charts.add_argument("--only", default=None, help="one chart's file name, or a day's number")
    charts.set_defaults(func=cmd_gallery)

    snapshot = sub.add_parser("chains", help="store option-chain snapshots from Yahoo Finance, or list them")
    snapshot.add_argument("action", choices=["fetch", "list"])
    snapshot.add_argument("tickers", nargs="*", default=["^SPX", "SPY", "AAPL"])
    snapshot.set_defaults(func=cmd_chains)
    return parser


def main(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
